### ISSUE TITLE
Alert: `ref` is not a prop

### ISSUE THREAD

**Issue by jrock17** [plougsgaard/react-timeout#119]
Getting this React warning from this component. Any ideas of a fix?

![2019-11-06_11-51-25](https://user-images.githubusercontent.com/1270524/68332624-fdfea680-008b-11ea-8a70-92c7a0d4c566.png)

**Comment by plougsgaard** [comment]
I haven't seen this myself, but it could be to do with (recent?) changes in React. Which version are you running and are you just using the package normally? I assume you're not messing around with refs or anything.

**Comment by ldanet** [comment]
Same here with a slightly different message:
![Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? Check the render method of `ReactTimeout`](https://user-images.githubusercontent.com/6631995/70180835-a3697080-1745-11ea-9976-967d7c065e70.png)
Using React@16.12.0

**Comment by plougsgaard** [comment]
Thanks for the confirmation @ldanet - I probably have to put together a version that's more suited for "new React"!

**Comment by jrock17** [comment]
Sorry for the delayed response. I'm using 16.8.3 and nothing funky with refs.

I think react-timeout is using 'ref' and recent versions of React throw this warning. Here is some info: https://stackoverflow.com/questions/38089895/react-ref-is-not-a-prop

**Comment by ziaulrehman40** [comment]
This is keeping me from using this library.

**Comment by plougsgaard** [comment]
Will look at it shortly.

**Comment by ziaulrehman40** [comment]
Thanks a lot @plougsgaard for your efforts. :+1:

**Comment by jrock17** [comment]
Any update on this one? Thanks!

**Comment by pnghai** [comment]
I got the same error, too

**Comment by afilp** [comment]
Does someone know what needs to be changed in the code in order for the `React.forwardRef` to work properly? 
As it is now we cannot have access to the wrapped component.
