### ISSUE TITLE
 ReactTimeout: React.createClass is deprecated and will be removed in version 16.

### ISSUE THREAD

**Issue by greenreign** [plougsgaard/react-timeout#13]
react: 15.5.4
react-timeout: 1.0.0

Fix React warning for deprecated createClass

'Warning: ReactTimeout: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.'

**Comment by plougsgaard** [comment]
Thanks for bringing this up! I'll have a look at it shortly. 👍

**Comment by plougsgaard** [comment]
I've released a patch `1.0.1` that fixes this.

**Comment by greenreign** [comment]
That did it.  Awesome, thanks!
