### ISSUE TITLE
setInterval only executes the passed callback once

### ISSUE THREAD

**Issue by jew-er** [plougsgaard/react-timeout#137]
When this component is loaded, the log statement prints only once (like setTimeout) instead of repeatedly at even intervals.

React versions I tested with - 16.13.0 and 17.0.1(with create-react-app)
react-timeout version - 2.0.0

`const Test = ReactTimeout(
(props: any) => {
  useEffect(() => {
     props.setInterval(() => {
      console.log("THIS RUNS ONLY ONCE")
    }, 500)
  }, [])
  return (
    <div> HELLO</div>
  )
})`

**Comment by jew-er** [comment]
After a bit of playing around with the packages code I found out that deleting line 12 from index.js:
`      _clearer.call(this, id)
`
will make setInterval behave properly, while still clearing it before the component is unloaded

**Comment by plougsgaard** [comment]
Thanks for reporting this @jew-er! 🎈
