### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by nathanielparry** [plougsgaard/react-timeout#16]
I'm getting this error while the component is still mounted. When the component unmounts it functions as expected. But when I navigate around the component this error pops up each time the timeout fires.

![screen shot 2017-05-16 at 1 33 33 pm](https://cloud.githubusercontent.com/assets/22308224/26124680/92fb365e-3a3c-11e7-9798-4ecada73953a.png)

An easy fix that I used:

```
     return function (callback, delta) {
       var id = _setter(function () {
         _clearer.call(this, id)

        // added conditional check for the callback argument
         callback && callback.apply(this, arguments)

       }.bind(this), delta)

```

**Comment by plougsgaard** [comment]
Could you share a snippet of how you're calling the timeout?

It looks as though it's being called with an `undefined` callback function.

I agree it should handle that case gracefully. I'll look into it in any case. Thanks for reporting this.

**Comment by nathanielparry** [comment]
```
if (!allLoaded) {
	if (loadedPercentage === 100) {
		this.props.loaded()
	}
	if (loadedPercentage !== 100) {
		this.props.setTimeout(this.props.loaded(), 3500)
	}
}

**Comment by plougsgaard** [comment]
@nathanielparry I would guess that the `setTimeout` line should look like this (without the `loaded` function called)

`this.props.setTimeout(this.props.loaded, 3500)`

Not knowing what the `loaded` function looks like I can't be sure of course. 😄 

I see that small mistake a lot when reviewing code. Let me know if that's the case!

**Comment by nathanielparry** [comment]
Sorry for the delay.

I've tried the above, and it didn't make any difference. I'm still getting the same error.

Any other thoughts?

**Comment by plougsgaard** [comment]
I'm now thinking your `loaded` function lives on the same component that sets the timeout? 

```
if (!allLoaded) {
   if (loadedPercentage === 100) {
      this.loaded()
   }
   if (loadedPercentage !== 100) {
      this.props.setTimeout(this.loaded, 3500)
   }
}
```

**Comment by nathanielparry** [comment]
No, it's in a higher-level component, which is why it's being passed through props.

**Comment by nathanielparry** [comment]
No, it's in a higher-level component, which is why it's being fed down through props.

**Comment by yoieh** [comment]
same issue here:

```
import React, { Component } from 'react';
import ReactTimeout from 'react-timeout';

class TestComponent extends Component {
  
  next = () => {
    console.log('next');
  }
  
  componentDidMount = () => {
    this.props.setTimeout(this.next(), 5000)
  };

  render() {
    return </div>;
  }
}

export default ReactTimeout(TestComponent );
```

runs log att componentDidMount and en after 5000 ms I get
error:
```
reactTimeout.js:12 Uncaught TypeError: Cannot read property 'apply' of undefined
    at ProxyComponent.<anonymous> (reactTimeout.js:12)
```


"react": "^16.3.1",
"react-timeout": "^1.1.1",
