### ISSUE TITLE
setTimeout doesn't fire again?

### ISSUE THREAD

**Issue by nealoke** [plougsgaard/react-timeout#9]
Hi! Currently the setTimeout only fires `this.autoSave()` 2 times and then stops? (components is not unmounted in meantime)

```
componentDidMount() {
	this.props.setTimeout(() => this.autoSave(), 1000);
}
```

**Comment by nealoke** [comment]
whoops, my bad ;) misplaced the call ;)

**Comment by VeeShostak** [comment]
Btw,
for anyone who wants to execute a certain block of code for x=5 seconds, this is how you can do it:
```
const getHumanResponse = () => {
    console.log('test!!!');
 }

for (let i = 1; i < 6; i++) {
    this.props.setTimeout(getHumanResponse, 1000 * i);
}
```

if you don't include the `1000 * i` it will try to execute 5 times at the same time (since all 5 timeouts are set to execute exactly after 1000 ms)
